### ISSUE TITLE
  Status roll back.

### ISSUE THREAD

**Issue by jpker** [crowdint/blog.crowdint.com#9]
Able to roll back any status of a blog post.

Example:

From Reviewed to Finished, Finished to Draft, etc.

Esteban, Yotzín, the author of the post should be able to do this.

**Comment by FerPerales** [comment]
Sometimes you change by accident the status of a blogpost and there's no way to make it go back to the previous state: i.e. a post published by accident, should be able to be marked as 'reviewed' again using the same admin interface.

I think this issue is valid, but that feature belongs to the [engine](https://github.com/crowdint/crowdblog)

**Comment by mumoc** [comment]
@FerPerales  Then, could you please move it there? or create this same issue there?

**Comment by FerPerales** [comment]
I'll create an issue there and reference it to this one. Is probable that, besides the changes in the engine, we may need to do some changes here

**Comment by FerPerales** [comment]
Creating the issue in the other repo. Even can close this
